### ISSUE TITLE
Error when connecting to Ledger from ICONex Chrome extension ("Failed to connect")

### ISSUE THREAD

**Issue by anomogh** [icon-project/ledger-app-icx#1]
**Environment:**
Windows 10
Chrome Version 67.0.3396.99 (64-bit)
ICONex 1.0.2.13
Icon Ledger app 0.1.0

**Steps to reproduce:**
1. In ICONex > My Wallet, click "Connect to Ledger"
 - "Connect to Ledger Wallet" dialog appears

2. Connect Ledger to PC & open ICON app on Ledger 
 - Ledger is displaying this text: "Start Wallet (ICX)" 

3. In the "Connect to Ledger Wallet" dialog, click the "Connect" button
 - the "Connect" text on the button turns into an animated spinner for a couple of seconds, 
 - then an empty "Wallet Address" table pops up very briefly 
 - and finally, the "Connect to Ledger Wallet" dialog reappears with the error message: "Failed to connect" "Please check the connection and click the “Retry” button below."

**Additional remarks:** 
- The error doesn't always occur, sometimes connecting works fine in the (seemingly) exact same scenario. Subjectively, I'd say in 10% of the cases...
- When clicking "Retry", the same error scenario plays out most of the times. But, occasionally, it works i.e. the Wallet Address table appears, showing five Icon addresses.
- In Chrome Developer tools, I can see five POST requests to https://wallet.icon.foundation/api/v2 (one for each of my public ICX Ledger addresses). The response status code is always 200 OK. This is true **even when the error occurs**.
- In the Developer Console, the following error is logged when Ledger fails to connect (I don't know if it still appears when the Ledger connects successfully, I couldn't manage a successful connection after it occurred to me to look at the Console...):
```
hardwallet.icon.foundation/static/js/main.bb99ad2c.js:1 Error: new BigNumber() not a number: undefined
    at N (hardwallet.icon.foundation/static/js/main.bb99ad2c.js:1)
    at hardwallet.icon.foundation/static/js/main.bb99ad2c.js:1
    at new t (hardwallet.icon.foundation/static/js/main.bb99ad2c.js:1)
    at c (hardwallet.icon.foundation/static/js/main.bb99ad2c.js:1)
    at hardwallet.icon.foundation/static/js/main.bb99ad2c.js:1
    at Array.map (<anonymous>)
    at t.value (hardwallet.icon.foundation/static/js/main.bb99ad2c.js:1)
    at Cn (hardwallet.icon.foundation/static/js/main.bb99ad2c.js:1)
    at An (hardwallet.icon.foundation/static/js/main.bb99ad2c.js:1)
    at $n (hardwallet.icon.foundation/static/js/main.bb99ad2c.js:1)
```
- Other people on reddit [reported the same error](https://www.reddit.com/r/helloicon/comments/95jrac/failed_to_connect_please_check_the_connection_and/).

**Comment by cwkwak** [comment]
Thank you for your report. We'll take a look into it.

**Comment by cwkwak** [comment]
Sorry for the inconvenience. 

Did you try to connect with Ledger on ICONex while Ledger Live or Ledger Manager chrome app is running? If so, please close Ledger apps, restart ICON app on ledger, and try to connect from ICONex again.

And also check device drivers for Windows. Please refer to the ledger connection issue page at https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Fix-connection-issues.

**Comment by anomogh** [comment]
After further experiments, it looks like **in my case the issue is caused by Malwarebytes for Windows**. On the Ledger support page that you linked one of the suggestions is to "Turn OFF VPN and anti-virus".

These are the **two solutions that worked** for me:

1. either turn off Malwarebytes completely while working with IconEX and Ledger
2. or add _chrome.exe_ to the Malwarebytes exclusion list

Afterwards, everything worked perfectly. 

For what is worth, I've never had any anti-virus related problems with Ledger until now. I've used Ledger successfully, both from Chrome with the [Stellar Account Viewer](https://www.stellar.org/account-viewer/#!/) (which is not a Chrome extension, though, just a site) and from [Neon Wallet](https://neonwallet.com/) (desktop application). I'm only mentioning this in case it helps you guys figure out how to stop these Ledger connection faults when AV software is running. It would be great if we didn't have to mess with our anti-virus configuration!

Thank you for your support and keep up the good work! :)

**Comment by cwkwak** [comment]
Happy to hear you found a solution. 

And we totally agree with your comment on using ICONex along with AV software. We'll keep finding a solution.

**Comment by Cryptoneer** [comment]
I'm having this exact issue too. Got it to connect once ok but haven't been able to get it to work again. More reports of the problem over on Reddit... you definitely have an issue here.

**Comment by grahmani** [comment]
Hi. I'm having the same problem and haven't been able to connect my ledger to ICONex even once. why can't you use ledger for ICX like other coins? I mean, inside of ledger live, make an accountand use it easily?
I use windows 10 64 bit.

**Comment by cwkwak** [comment]
We're thinking of creating an app in Ledger Live, but don't have a specific plan yet. First, we'll focus on fixing the problem on ICONex.

**Comment by davmjohansson** [comment]
I am having the same issue. Am not able to connect to it even once. Tried on two different computers. I already have the icon app installed.

**Comment by cwkwak** [comment]
Please check the followings
1) if Ledger Live or Ledger Manager is working properly just for checking if USB connection and ledger device is working.
2) if ICONex is running without Ledger Live, Ledger Manager, or any other Ledger related apps.
3) if you opened ICON app on Ledger device before trying to connect from ICONex.

Everything is satisfied, then any more information would be helpful.

And we plan to perform more tests on Windows systems and figure out symptoms.

**Comment by grahmani** [comment]
1- Yes ledger live is working properly. I moved some other coins there. 
2- ICONex is opened without any problem. actually I don't have an ICONex account, but when ICONex comes up, there is 3 options, create wallet, load wallet, and connect to ledger.
first two options seems to work properly, and the third one, when click on it and then open the ICON on ledger and then click connect, it tries to connect, and it connects for 1 second and then comes out and this message pops up: "Failed to connect" "Please check the connection and click the “Retry” button below." and this keeps happening always.
3- yes, it is opened.

**Comment by cwkwak** [comment]
As for the 2nd step, you didn't run ICONex and Ledger Live (or Ledger Manager) at the same time, did you?
And what is your OS?

**Comment by grahmani** [comment]
and the 2nd step, I tried both with and without ledger live running, and didn't open ledger manager.
windows 10 64 bit.

**Comment by grahmani** [comment]
and this is my telegram ID. try to send me a pm, and I send you a 10 second video how this is happening.
@dejavuou

**Comment by davmjohansson** [comment]
Same for me, 1.2.3. Is tried and still get failed to connect. Issue might be that I am in China and need to use a VPN, but this is not an issue for other ledger apps such as NEO and others.

**Comment by davmjohansson** [comment]
Oh and I get the same issue on my macbook. Have tried both ways.

**Comment by aaaeeel** [comment]
у меня такая же проблема : (

**Comment by davmjohansson** [comment]
I seem to have found the issue to my failed to connect problem. It seems to work when I turn off my adblocker.

**Comment by shajimanghat** [comment]
I have been trying to connect ledger nano s to iconext  for the past 1 week,  I am getting failed to connect message.  Sirs, kindly guide and help . I am not a technical person . Please deeply appreciate help

**Comment by cwkwak** [comment]
We **FIXED** a couple of timing issue which seem to be related to the connection problems. You don't need to update the ICONex app. All are fixed on the server side.
And we are expecting that you won't have the problem even with Anti-Virus software running.

Please try to connect and let us know if connection problems still happen.

**Comment by anomogh** [comment]
I can confirm that connection problems have disappeared for me, even with anti-virus (Malwarebytes) running. It works perfectly now.

**Comment by shajimanghat** [comment]
Dear Sir
Thank you very much  for your kind support. Please accept my gratitude for
the same .I shall check and let you know

Regards
Shaji

**Comment by shajimanghat** [comment]
Dear Sir

I have tried to connect still getting "Failed to Connect" message.  Rest
all coins wallet like neo, tron are working in Ledger Nano except ICON.
Kindly advise what could be the reason.  I tried with a different lap top
and even my one of friends is also getting same message.

Kindly help to resolve the issue

Regards
Shaji

**Comment by shajimanghat** [comment]
Sir, even I downloaded latest iconex wallet and tried to connect still getting same message. Even my friend tried to connect he is also getting same failed to connect msg. Rest all coins are working in ledger nano like tron neo etc except Icon

**Comment by shajimanghat** [comment]
Dear Sir,

Now it is working.  I updated both icon wallet with ledger live and down loaded again google extension. Now it is working well.  I would like to express deep felt gratitude for the kind support.   I pray for the ICON community for the excellent support.  I  am fan of ICON and personally  responsible for advising my whatsgroup of about 26 people to invest into ICON. We all are now transfering to Ledger nano.

Once again Love to Icon Community for the spontaneous help.

**Comment by cwkwak** [comment]
Good to hear that.
Many thanks for your interest in ICON.

**Comment by velvetalley** [comment]
Hey there:

I am having the same issue and judging by the comments on Reddit, a number of others are having this issue as well.  I have downloaded the Icon App from Ledger Live and I have also downloaded the Iconex extension.  All of my other wallets for other crypto work perfectly within Ledger.  However, Icon will not work.  I get an error that says "Failed to Connect" every single time.  I want to get the swap done within my ledger.  I have tried on a Windows 10 computer as well as my Windows 7 computer.  Same problem every time.  I have tried uninstalling and reinstalling both the app and the Iconex extension multiple times.  I have also disabled my antivirus.  I have closed Ledger Live before accessing the Iconex Extension.  Nothing seems to help.  I have not been able to access the wallet once and have tried clicking "Connect" and then "Retry" dozens of times.  Every single time it fails.  I'm happy to provide any additional information you need to review.  Please let me know.  Thanks.

**Comment by shajimanghat** [comment]
You may kindly  uninstall the icon app from ledger live  and re-install
Then uninstall the google extension  inconex and reinstall
Server side issues are ok now
Then kindly try again, it will work, for me it worked now.

**Comment by mksong76** [comment]
It comes from timeout parameter in ICONex. ICONex has changed those parameters in their release. We close this issue. If you see still this issue, please report them in other issue.

**Comment by bz7593** [comment]
hi everyone i have probleme 
- i conect my ledger and i can open my iconex wallet
- but when i want to send transfer my icx i receive this message after pressing ok on my hardwar ledger
and the message is * Failed to connect. Please try again. * since 3 days i try ... can someone help ?? plz

**Comment by cwkwak** [comment]
Please refer to [https://github.com/icon-project/ledger-app-icx/issues/2](https://github.com/icon-project/ledger-app-icx/issues/2)
